// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ay05Lbdh9hWXi30fx1LUqWHJCCyDeb4',
    appId: '1:82617006469:web:990356b182cb04f65aecec',
    messagingSenderId: '82617006469',
    projectId: 'biy-daalt-7b24e',
    authDomain: 'biy-daalt-7b24e.firebaseapp.com',
    storageBucket: 'biy-daalt-7b24e.firebasestorage.app',
    measurementId: 'G-SZ3STFCBB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBZgkqRHp9AR9BRwopCWvwQpQLH7_KnE',
    appId: '1:82617006469:android:471e60f396dde7835aecec',
    messagingSenderId: '82617006469',
    projectId: 'biy-daalt-7b24e',
    storageBucket: 'biy-daalt-7b24e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWzRZR20lhceTRjDM6oWC9kF8tm_F2Ow',
    appId: '1:82617006469:ios:075dff89bc2cdbdb5aecec',
    messagingSenderId: '82617006469',
    projectId: 'biy-daalt-7b24e',
    storageBucket: 'biy-daalt-7b24e.firebasestorage.app',
    iosClientId: '82617006469-esn4qe0v8h44pkp8iuji4trbi8mcatbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.biyDaalt1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFWzRZR20lhceTRjDM6oWC9kF8tm_F2Ow',
    appId: '1:82617006469:ios:075dff89bc2cdbdb5aecec',
    messagingSenderId: '82617006469',
    projectId: 'biy-daalt-7b24e',
    storageBucket: 'biy-daalt-7b24e.firebasestorage.app',
    iosClientId: '82617006469-esn4qe0v8h44pkp8iuji4trbi8mcatbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.biyDaalt1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ay05Lbdh9hWXi30fx1LUqWHJCCyDeb4',
    appId: '1:82617006469:web:3fd91ab63977f38e5aecec',
    messagingSenderId: '82617006469',
    projectId: 'biy-daalt-7b24e',
    authDomain: 'biy-daalt-7b24e.firebaseapp.com',
    storageBucket: 'biy-daalt-7b24e.firebasestorage.app',
    measurementId: 'G-RTNDWTV4MM',
  );
}
